### model
model_name_or_path: Qwen/Qwen3-4B-Instruct-2507
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: custom_assistant
template: qwen3_nothink
cutoff_len: 1024
max_samples: 1000
val_size: 0.2
preprocessing_num_workers: 4
dataloader_num_workers: 2

### output
output_dir: saves/qwen3-4b-custom/lora/sft
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # Choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false  # Change to true if supported by GPU
fp16: false  # Change to true if running on older GPUs
ddp_timeout: 180000000

### eval
eval_dataset: custom_assistant
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10
